name: .NET

on:
  push:
    branches: [ main, 'version/**', 'pr/**', 'pr-**' ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main, 'version/**', 'pr/**', 'pr-**' ]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore ./Src/VirtualFileSystem.sln
    - name: Build
      run: dotnet build --no-restore ./Src/VirtualFileSystem.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Src/VirtualFileSystem.sln
